sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pujapunchouty/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pujapunchouty/docker-react npm run test
