version: 2.1

jobs:
  build:
    docker:
      - image: pujapunchouty/docker-react
    steps:
      # - checkout
      - run: echo "Puja Says Hello from circle ci config file"
      - run:
          name: Package install
          command: npm install
      - run:
          name: Run tests
          command: npm test

    