version: 2.1

jobs:
  build:
    docker:
      - image: pujapunchouty/docker-react
    steps:
      - checkout
      - run : echo "Puja Says Hello from circle ci config file"
      - run:
          name: Run tests
          command: npm test

    